### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by gabzsa** [justinleewells/pogo-optimizer#10]
I get this after `node index` in wildcard.js:8

```
const HOSTNAME_REGEX = /^(.+)(\.[^\.]{4,}(\.[^\.]{1,3})*\.[^\.]+)$/;
^^^^^
SyntaxError: Use of const in strict mode.
```

I have already git pull to the latest (I saw the exact same problem was fixed, but I am still seeing it).
- npm version is 3.10.6
- node version is 0.12.0
- using OSX

**Comment by xenob8** [comment]
update node version!

**Comment by gabzsa** [comment]
Thank you. Now I get `Error: Module version mismatch. Expected 48, got 14.`

in `node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf/node_modules/bindings/bindings.js:83`
