### ISSUE TITLE
MacOS running, Profile Can't be installed.

### ISSUE THREAD

**Issue by t2ac32** [justinleewells/pogo-optimizer#103]
So i managed to run.
already configured my phone with my computer's ip and port 8081 as proxy.
Checked i could log in into the game and i can.

But every time i go directly to http://localhost:3000/#/connect 
i'am prompted with 
`Please enable the proxy on your phone,
download the certificate,
and log in to the game `

this got me thinking should i installed the certificated in my phone or in my computer.
i tried installing it in my phone but the installation fails.

Installing the certificate in the computer work, the certificate was manually validate (just in case) because the certificated marked invalid.

Any ideas?

**Comment by justinleewells** [comment]
You have to download the certificate on your phone.

**Comment by t2ac32** [comment]
ok so i tried by installing the certificate on my phone but safari prompts a message saying the install failed by an know error any ideas?

**Comment by t2ac32** [comment]
Progress:

Ok so i updated my local repository with a: git pull
after that i notice the Terminal installation instructions changed.
Y Ran every command for npm.

Now i have managed to install the profile successfullym but i'm still seeing arceus screen.

**Comment by justinleewells** [comment]
Did you close and reopen the game after installing the certificate?

**Comment by t2ac32** [comment]
Thanks yep i had already opened and closed. Seems the last error was due to my router blocking the game.

Thanks amazing app.

**Comment by justinleewells** [comment]
Glad you go it working. Happy hunting!
