### ISSUE TITLE
Explanation for CP%

### ISSUE THREAD

**Issue by unfulfulledgamer** [justinleewells/pogo-optimizer#107]
This column is a bit confusing. Is it the percentage the pokemon is at on the cp arc or it is the percentage that will they max at compared to a perfect pokemon?

**Comment by justinleewells** [comment]
The percentage they will be at max compared to a perfect Pokemon. Where you are on the arc is level.

**Comment by unfulfulledgamer** [comment]
thanks !

**Comment by gvdn78** [comment]
Would u Mind explaining the cp% a bit more? What is used to determine the %? Does it take into account the moves the Pokemon has? What do u mean with perfect Pokemon ? Just the amount of IV they have? Thanks

**Comment by gvdn78** [comment]
Would u Mind explaining the cp% a bit more? What is used to determine the %? Does it take into account the moves the Pokemon has? What do u mean with perfect Pokemon ? Just the amount of IV they have? 
What is best to determine which one to keep? IV % or cp% ? Thanks again.

**Comment by mathiasbynens** [comment]
Perhaps a short description could be added to the `title` attribute of each `<th>` element.

**Comment by mathiasbynens** [comment]
@gvdn78

> What is best to determine which one to keep? IV % or cp%?

They’re related and based on the same numbers. See https://github.com/justinleewells/pogo-optimizer/blob/ea0234645778e55c5f74be6a97af0fc8d9417de1/lib/pokemon.js#L26-L28 and https://github.com/justinleewells/pogo-optimizer/blob/ea0234645778e55c5f74be6a97af0fc8d9417de1/lib/pokemon.js#L41-L44. Keep the ones with the best IV%.

**Comment by justinleewells** [comment]
Additionally, I may include a section in the README about the different values.

**Comment by weblack** [comment]
The iv and cp percentages I find can be misleading. As different Pokemon have different max cp levels, the implications of a lower max cp isn't as great for say Onyx compared to Dragonite.

At the end of the day cp is king and iv is used to calculate it. Maybe a metric that describes the lost cp potential would be more informative?
