### ISSUE TITLE
Why not just include a guide to installing an ubuntu vm for windows users?

### ISSUE THREAD

**Issue by water42** [justinleewells/pogo-optimizer#111]
1. Install oracle VM virtualbox
2. Download then create an Ubuntu 16.04 VM
3. Run terminal command Ifconfig to get local address of the VM
4. Use local address to create proxy

I don't know if this is easier but it should have a 100% success rate.

Awesome app!

**Comment by therealklanni** [comment]
Probably easier to just run it in Docker. There are instructions for getting started with Docker on Docker's site.

(I think this issue can be closed)

**Comment by water42** [comment]
From the README: "Currently, it is very difficult to get this program working on Windows. Until a fully javascript implementation of protobuf can be utilized, Windows support will not be provided. For the time being, the recommended solution is Docker. If anyone would like to contribution documentation on how to get this project running flawlessly on Windows with Docker, please contact me."

This led to me to assume that the docker method was inconsistent and buggy, so I didn't bother with it. Anyways closing.

**Comment by justinleewells** [comment]
That was actually put there when we had JUST added the Docker method. There's still not really any doc on using netsh for Windows, though.
