### ISSUE TITLE
[Feature Req.] Nickname change

### ISSUE THREAD

**Issue by fbatista** [justinleewells/pogo-optimizer#120]
Would it be possible to change the pokemon nicknames through the web interface via calls to the API? or would that be a breach of the niantic TOS ?

I can see it being an amazing feature as in: connect to the proxy, and all my collection gets updated with the IV% or anything else that we could easily configure, in the pokemon nickname.

**Comment by justinleewells** [comment]
It would be a breach of the Niantic TOS. I actually had this implemented to some extent, but not exposed to the user, and I decided against it. We're going to comply with the ToS as much as possible so Niantic doesn't shut us down.

**Comment by fbatista** [comment]
Awesome, let's hope Niantic comes forth with an official API that supports actually doing these kind of things!
