### ISSUE TITLE
FEATURE REQUEST - Sort pokemon by recently caught.

### ISSUE THREAD

**Issue by Pygums** [justinleewells/pogo-optimizer#121]
In game you can sort by recently added pokemon.  Makes it easier to find the newest additions to the bag and check their IV's at a glance, rather than needing to sort through the 100+ we might have sitting around. 

Just a quality of life thing when possible.

**Comment by justinleewells** [comment]
This was added in justinleewells/pogo-optimizer#117

**Comment by Pygums** [comment]
Awesome Thanks.  Will that be out with an update or do i need to do that myself?

**Comment by justinleewells** [comment]
You'll have to re-pull the repo and rebuild the Docker image if you're using Docker.

**Comment by Pygums** [comment]
I installed it via Ubuntu VM.  What lines would i need to run again in order to update it?  I'm not too familiar with all this so thanks for the help

**Comment by justinleewells** [comment]
It should just be `cd pogo-optimizer && git pull && npm start`.

**Comment by Pygums** [comment]
Fantastic, thanks
