### ISSUE TITLE
Android device "Cannot GET /ca.crt

### ISSUE THREAD

**Issue by venounan** [justinleewells/pogo-optimizer#122]
I got the program running on my mac, and am visiting the website and I see the screen where it tells me to "Please enable the proxy on your phone, download the certificate, and log in to the game"

When I go to the same ip/ca.crt it only gives me a message that says "Cannot GET /ca.crt"

**Comment by justinleewells** [comment]
Does the Arceus screen show at ip:3000?

**Comment by venounan** [comment]
Yes, on both the phone and on my laptop

**Comment by venounan** [comment]
I am running android 6.0.1 which some other devices have had issues with, so I installed the Root Certificate app, and am trying to send the file over manually to my phone to install, but when on my laptop I go to ip:3000/ca.cert I get the same "cannot GET /ca.crt" message

**Comment by justinleewells** [comment]
Which version of the app are you using? It seems to me that it's not generating the ca.crt correctly.

**Comment by justinleewells** [comment]
I just tested it on the newest version and it generated the ca.crt correctly.

**Comment by venounan** [comment]
I just pulled it from this repo using the "git clone https://github.com/justinleewells/pogo-optimizer" maybe an hour ago now?

**Comment by justinleewells** [comment]
Ah, you're not using Docker so it wasn't generated. I should have caught that. Run `openssl x509 -inform PEM -outform DM -in /code/.http-mitm-proxy/certs/ca.pem -out /code/.http-mitm-proxy/certs/ca.crt;` inside the directory.

**Comment by venounan** [comment]
```
openssl x509 -inform PEM -outform DM -in /code/.http-mitm-proxy/certs/ca.pem -out /code/.http-mitm-proxy/certs/ca.crt;
Error opening Certificate /code/.http-mitm-proxy/certs/ca.pem
27703:error:02001002:system library:fopen:No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.40.2/src/crypto/bio/bss_file.c:356:fopen('/code/.http-mitm-proxy/certs/ca.pem','r')
27703:error:20074002:BIO routines:FILE_CTRL:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.40.2/src/crypto/bio/bss_file.c:358:
unable to load certificate
```

**Comment by justinleewells** [comment]
Oh, sorry. That's from the Dockerfile. It would be:

`openssl x509 -inform PEM -outform DM -in ./.http-mitm-proxy/certs/ca.pem -out ./.http-mitm-proxy/certs/ca.crt;`

**Comment by venounan** [comment]
That did it! Perfect. Can I suggest adding it to the OSX tutorial?

**Comment by justinleewells** [comment]
I'm going to rewrite all of the documentation tonight. Happy hunting!

**Comment by venounan** [comment]
Thank you very much for the help! This is the exact tool I've been looking for.
