### ISSUE TITLE
Cannot GET / ca.crt

### ISSUE THREAD

**Issue by xcheneric** [justinleewells/pogo-optimizer#127]
I can't download the ca.crt using the xxx.xxx.xx.x:3000/ca.crt link on my android phone. Converting the pem file to crt via ssh and importing throught root certificate manager doesn't work.

After setting up the wifi proxy, I can't browse to any site because I don't have the right certs.

I've tested my setup with an iphone and I got it to work, so the issue is with the certs on android (6.0.1).

**Comment by xcheneric** [comment]
Using this actually worked: http://www.realmb.com/droidCert/

This is a good work around while this gets fixed.

**Comment by justinleewells** [comment]
v1.3.0 actually has .crt generation implemented. Should be out in a few hours!

**Comment by xcheneric** [comment]
Do I have to get a new cert every time I switch networks?

**Comment by justinleewells** [comment]
No, but you will have to update it every time you pull a new Docker container, assuming you're using Docker.

**Comment by xcheneric** [comment]
What about different computers? I'm on ubuntu.

**Comment by justinleewells** [comment]
Yeah, each computer generates a different ca.pem/ca.crt
