### ISSUE TITLE
Plan for updating already found pokemon stats

### ISSUE THREAD

**Issue by queso** [justinleewells/pogo-optimizer#13]
Hey @justinleewells, what is the plan for tracking/updating stats? I think this will be a more urgent issue with how the MITM module (or the actual Api) is returning only changed data now, which will cause your list to be wiped out.

**Comment by queso** [comment]
It seems like we are getting a unique id passed along with each pokemon caught:

```
{ id: '16681031934620772887',
  pokemon_id: 'RATTATA',
  cp: 108,
  stamina: 24,
  stamina_max: 24,
  move_1: 'TACKLE_FAST',
  move_2: 'DIG',
  height_m: 0.30604124069213867,
  weight_kg: 3.2440361976623535,
  individual_attack: 7,
  individual_defense: 6,
  individual_stamina: 6,
  pokeball: 1,
  captured_cell_id: '9817931850063020032',
  creation_time_ms: '1468881961414' }

```

**Comment by justinleewells** [comment]
I'm about to rewrite the way that it stores the Pokemon now. This project will be re-written in the very near future, though, so we can switch to Electron and make it a lot more user-friendly.

**Comment by queso** [comment]
I think it would make a lot more sense to move to an easy to use DB? Would make it easier to add search/filter, etc.

**Comment by justinleewells** [comment]
I want to keep everything local and the dependencies low, so we'll see. We'll only be dealing with a few hundred entries at once, so it wouldn't be that hard to just liberally use lodash to keep track of Pokemon.
