### ISSUE TITLE
Can't seem to get it to run on OS X El Capitan

### ISSUE THREAD

**Issue by brettonlewis** [justinleewells/pogo-optimizer#131]
Here is the log:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.3.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pogo-optimizer@1.3.0~prestart: pogo-optimizer@1.3.0
6 silly lifecycle pogo-optimizer@1.3.0~prestart: no script for prestart, continuing
7 info lifecycle pogo-optimizer@1.3.0~start: pogo-optimizer@1.3.0
8 verbose lifecycle pogo-optimizer@1.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle pogo-optimizer@1.3.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/pogo-optimizer/node_modules/.bin:/usr/local/Cellar/node/6.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/git/bin
10 verbose lifecycle pogo-optimizer@1.3.0~start: CWD: /usr/local/pogo-optimizer
11 silly lifecycle pogo-optimizer@1.3.0~start: Args: [ '-c', 'gulp && node index' ]
12 silly lifecycle pogo-optimizer@1.3.0~start: Returned: code: 1  signal: null
13 info lifecycle pogo-optimizer@1.3.0~start: Failed to exec start script
14 verbose stack Error: pogo-optimizer@1.3.0 start: `gulp && node index`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid pogo-optimizer@1.3.0
16 verbose cwd /usr/local/pogo-optimizer
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error pogo-optimizer@1.3.0 start: `gulp && node index`
22 error Exit status 1
23 error Failed at the pogo-optimizer@1.3.0 start script 'gulp && node index'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pogo-optimizer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp && node index
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pogo-optimizer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pogo-optimizer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dneal12** [comment]
Same happened for me.  An older version worked fine.  But I get this error when trying the latest.

**Comment by justinleewells** [comment]
Fixed in justinleewells/pogo-optimizer@29dfdd5
