### ISSUE TITLE
No return from port 3000

### ISSUE THREAD

**Issue by VincentWyin** [justinleewells/pogo-optimizer#139]
Start success, phone connected and data found in data/save/<account name>

However, nothing found in port 3000. Please advise. Thanks in advance.

**Comment by justinleewells** [comment]
There's not even an Arceus page? Are you visiting localhost:3000?

**Comment by t2ac32** [comment]
you should at least see the arceus background.
If you re seeing the arceus background on the assumption everything is working try to restart the pokemon go app, while the server is running.

**Comment by VincentWyin** [comment]
Thanks for all replies, I have tried localhost:3000 and 192.168.xxx.xxx:3000. Both of them are blank and only show the page title and icon. 

There is no arceus background.

**Comment by VincentWyin** [comment]
Please close this issue, it's caused by old version (1.2.0). Thanks.
