### ISSUE TITLE
The front-end page getting easy to stuck from certain version

### ISSUE THREAD

**Issue by ManiacMike** [justinleewells/pogo-optimizer#140]
The front end page getting easy to stuck from certain version when displaying, scrolling or sorting on the page.
My macbook pro is with a 2.4 GHz i5 cpu and ssd drive( is kinda old I guess),yet it can open long web pages like facebook or youtube very smoothly.
So I am wondering if you can so some changes with the front end page performance? That will be very appreciated. : )

**Comment by justinleewells** [comment]
There's a lot of binding that isn't very performant. I'll work on optimizing it tonight.

**Comment by justinleewells** [comment]
This should be fixed in justinleewells/pogo-optimizer@5f1e54f.

**Comment by ManiacMike** [comment]
Thanks man
