### ISSUE TITLE
How are iva ,ivd & ivs calculated?

### ISSUE THREAD

**Issue by t2ac32** [justinleewells/pogo-optimizer#141]
This is really not an issue but i've been going through the code to learn a bit more. Im interested in getting a port similar to pogo- optimizer into iPhone. 

while reading: 
> .determineMetadata

var pkmn = _.find(PokemonData, {name: this.data.pokemon_id});
  var cpm = this.data.cp_multiplier;
  if (this.data.additional_cp_multiplier) cpm += this.data.additional_cp_multiplier;
  var iva = this.data.individual_attack;
  var ivd = this.data.individual_defense;
  var ivs = this.data.individual_stamina;
  var ba = pkmn.stats.attack;
  var bd = pkmn.stats.defense;
  var bs = pkmn.stats.stamina;

I'm new with js. But i have almost everything figured out except the part where the individual values of the analyzed pokemon are obtained.
I'm making the assumption that ba,bd &bs are obtained from the pokemon.js file.

thanks on advance.

**Comment by justinleewells** [comment]
iva, ivd, and ivs are taken directly from the server.
