### ISSUE TITLE
unable to pull image

### ISSUE THREAD

**Issue by BASTAHT** [justinleewells/pogo-optimizer#142]
when running

docker run -d -p 3000:3000 -p 8081:8081 -it justinleewells/pogo-optimizer

first it looks locally for the image, then it tries to pull the image, but the connection times out:

Pulling repository docker.io/justinleewells/pogo-optimizer
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/justinleewells/pogo-optimizer/images. You may want to check your internet connection or if you are behind a proxy..

Also when I go to this URL I only see []

**Comment by justinleewells** [comment]
http://stackoverflow.com/questions/31990757/network-timed-out-while-trying-to-connect-to-https-index-docker-io
