### ISSUE TITLE
no such file or directory - ca.pem

### ISSUE THREAD

**Issue by Choque** [justinleewells/pogo-optimizer#146]
Getting the following error after running `npm start` on my RPi3 (Raspbian Jessie; Kernel version 4.1.19-v7+)

```
> pogo-optimizer@1.3.0 start /home/pi/pogo-optimizer
> gulp && node index

[21:43:12] Using gulpfile ~/pogo-optimizer/gulpfile.js
[21:43:12] Starting 'clean'...
[21:43:13] Finished 'clean' after 533 ms
[21:43:13] Starting 'jade'...
[21:43:13] Starting 'stylus'...
[21:43:13] Starting 'img'...
[21:43:13] Starting 'lib-js'...
[21:43:13] Starting 'lib-css'...
[21:43:13] Starting 'favicon'...
[21:43:13] Starting 'js'...
[21:43:13] Starting 'font'...
[21:43:15] Finished 'favicon' after 1.7 s
[21:43:15] Finished 'lib-css' after 1.74 s
[21:43:15] Finished 'stylus' after 2.53 s
[21:43:16] Finished 'lib-js' after 3.44 s
[21:43:16] Finished 'js' after 3.44 s
[21:43:16] Finished 'jade' after 3.59 s
[21:43:17] Finished 'font' after 4.25 s
[21:43:20] Finished 'img' after 6.79 s
[21:43:20] Starting 'default'...
[21:43:20] Finished 'default' after 40 μs
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
Accept the cert at 127.0.1.1:3000/ca.pem if you haven't already done so
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.http-mitm-proxy/certs/ca.pem'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.fs.readFileSync (fs.js:397:15)
  at [object Object]._onTimeout (/home/pi/pogo-optimizer/index.js:136:48)
  at Timer.listOnTimeout (timers.js:92:15)


npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.3.0 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pogo-optimizer@1.3.0 start script 'gulp && node index'.
npm ERR! This is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/pogo-optimizer/npm-debug.log
```

**Comment by justinleewells** [comment]
Pull the newest version.

**Comment by justinleewells** [comment]
I'll push a fix tonight. This isn't happening to most people. Somehow your computer is moving slowly enough that it doesn't beat the timeout. I'll just write something that checks every few seconds to see if the file exists.

**Comment by Choque** [comment]
Thanks for reopening the issue. I guess that's possible. After all it's only a RPi3 and behind a PiHole. So maybe that contributes to it.
Though it goes from `Accept the cert at 127.0.1.1:3000/ca.pem if you haven't already done so` to the error basically instantly

**Comment by lhung** [comment]
In the mean time, you can try uploading the ca.pem to your Google Drive or Dropbox and installing it from those locations instead. The file is under pogo-optimizer/.http-mitm-proxy/certs/ca.pem

**Comment by bensurman** [comment]
the latest pull didnt install the ca.pem for me, .http-mitm-proxy/certs/ is empty

**Comment by cooperdavidc** [comment]
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
Accept the cert at 192.168.0.7:3000/ca.pem if you haven't already done so
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.http-mitm-proxy/certs/ca.pem'
  at Error (native)

I have the same problem. Where can I download the cert?

**Comment by g3r4n** [comment]
```
npm install -g coffee-script
coffee node_modules/pokemon-go-mitm/example.logTraffic.coffee
```

**Comment by justinleewells** [comment]
Err, @g3r4n I'm not sure how that pertains to this ticket. Are you just telling them to run that script so it generates a cert?

v1.3.1 should have fixed ca.crt/ca.pem generation errors, even on a Raspberry Pi. Pull the newest code and you should be good to go.
