### ISSUE TITLE
[Doubt] How to reset current pokémon list

### ISSUE THREAD

**Issue by LasaFawkes** [justinleewells/pogo-optimizer#148]
I can't seem to reload the spreadsheet to show my current pokémon, it just adds the new ones to the list even if I have transferred them. Is there any specific command on Docker or something I'm missing here? Thank you <3

**Comment by macmanchomp** [comment]
I second this. I used the logout option to swap to my wife's pokemon go account and it seems none of our data shows anymore, likely because the logout button seems to act as a sort of ignore this user type of command. Perhaps adding a true refresh button to completely repopulate the list from scratch would work well? Just a suggestion.

**Comment by justinleewells** [comment]
I'm just going to make it so it wipes accounts when you log in/out. There's no real benefit to doing otherwise atm. That being said, it should be doing something similar to that atm. Did your wife completely close her app, turn on the proxy, and re-open it?

**Comment by macmanchomp** [comment]
yes sir, as a matter of fact, I have tried a complete data clear (equivalent to uninstall and reinstall) then even logged in fresh to the account while connected to the proxy, maybe something is wrong with the proxy configuration, though I know I can get to the website through the local ip on port 3000 eg. http://192.168.1.3:3000/. So I know I was configured to use the right address for the proxy, and no settings had been changed in the interim. I am currently installing fresh with the latest version available as of around 4pm today and will report back after with news on whether or not in functions to help narrow down what went wrong.

**Comment by ManiacMike** [comment]
cd pogo-optimizer 
rm -rf data/save/mike900125/

(mike900125 is my username). Relaunch the pokemon app will solve your problem

**Comment by macmanchomp** [comment]
Thanks Maniac Mike, unfortunately for me, I had already tried that, but at this point I'm thinking it could have been my server having issues, as I am now in the midst of reinstalling due to several issues involving networking that I can't be bothered to rummage around and fix being that the thing pretty much just had pogo and some old classwork from college on it.

**Comment by justinleewells** [comment]
v1.3.1 completely wipes data when you log out, so give that a go and tell me if it works for you.

**Comment by macmanchomp** [comment]
Thanks man, once I'm done reinstalling I'll hit it with some test cases.
Might have to be tomorrow depending on my internet... the infrastructure
out here is long range wifi so with the dust storms Internet gets pretty
slow....

**Comment by macmanchomp** [comment]
So far it is working pretty beautifully. Very clean, and the spreadsheet loads live so as I find pokemon species I don't see potential in and go hacking away transferring them all, when I look back up they're all gone! Well done sir!

**Comment by LasaFawkes** [comment]
I'm still having trouble :sob: I updated using Docker's `pull justinleewells/pogo-optimizer` and even tried using `rm -rf data/save/username/` (which, by the way, it's a folder I can't personally find under C:\Users\username\pogo-optimizer\data). I also tried logging out and then logging back in.

Having done that, it still shows an outdated list of pokémon for me. What am I doing wrong?

**Comment by macmanchomp** [comment]
I think someone covered some of those possibilities in another issue. I'm
not versed in docker, but it would make sense that there's something going
on with caching if you're not seeing any changes take place after updating.
The evolution chart should also be there, so if that's not visible on the
navigation bar at the top then you're not running the latest version. Try
checking the issues relating specifically to docker, they might shed a
little more light on what is happening. Good luck and sorry I couldn't be
of more use.

**Comment by LasaFawkes** [comment]
I already got it to work, thank you! You must have missed my edit on the previous post :)

**Comment by macmanchomp** [comment]
Yeah lol. I get email notifications and am just commenting through email.
Sadly it doesn't show edits :P.

**Comment by justinleewells** [comment]
I'm going to close this since you got everything working, @LasaFawkes.
