### ISSUE TITLE
Please add column BaseDPS or DPS% depending on possible Move-Combination per Pokemontype

### ISSUE THREAD

**Issue by clangdev** [justinleewells/pogo-optimizer#156]
Hi,
I would suggest to add another column to be able to compare Move-Combo per Pokemon-Race.
DPS is a nice thing but it reflects current value depending on level (and IV etc.).
To get base DPS I would just sum DPS-Move1 and DPS-Move2.
DPS% could be calculated by currentBaseDPS/theoreticalMaxBaseDPS for this Pokemon-Race.

Feel free to correct me or do it any better.
Although I know that Move-set change by evolution it would help to compare Pokemon.

**Comment by justinleewells** [comment]
The only reason I'm hesitant to do this is because the second move is currently garbage in like 90%+ of cases. You could submit a PR and make it an optional column if you really wanted it, but with the current state of the game, I'm not sure it's really a necessity.

**Comment by clangdev** [comment]
Well, 
one could work around that if there would be an option to order by Move(1/2)DPS(asc/desc).
I would like to order by #, IV%, Move1DPS,Move2DPS to get which Pokemon in my inventory is really the best.
I try by myself when I have more time to dig into your code.

**Comment by justinleewells** [comment]
The "DPS" column gives a pretty accurate picture of the damage potential of a Pokemon.

**Comment by clangdev** [comment]
Yes, but you cannot compare one pokemon to the other until they have same IV and same CP:
...
var atk = (ba + iva) * cpm;
...
var dps = atk * stab * (pow / (m1.DurationMs / 1000));
...

**Comment by justinleewells** [comment]
So you're saying DPS Potential rather than actual DPS. Fair enough. However, I still don't really think Special Moves should be included.

**Comment by clangdev** [comment]
Sry, I guess that's what I meant. English is not my native language. :-)
Special-Move maybe another discussion, I personally would include it to be able to compare it as well, although I think you're right, it is less important than Primary-Move.

**Comment by justinleewells** [comment]
Your English is fine! I just wasn't getting it. I'll try to add a DPSP (DPS Potential) column in the next release.
