### ISSUE TITLE
Clicking on pokemon shows NaN for height and weight

### ISSUE THREAD

**Issue by syclee** [justinleewells/pogo-optimizer#159]
Clicking on a pokemon brings up modal window displays NaN for height and weight. 

version commit: c7b5a7

<img width="464" alt="screen shot 2016-07-28 at 9 34 00 pm" src="https://cloud.githubusercontent.com/assets/4576303/17211179/45686446-550b-11e6-977a-988e943045e2.png">

**Comment by syclee** [comment]
Also, can I request that height and weight be added as a column? I used to use it to differentiate between pokemon of identical CP. I miss that from the old UI.

**Comment by justinleewells** [comment]
Fixed in justinleewells/pogo-optimizer#5f1e54f.
