### ISSUE TITLE
No Pokemon show at http://localhost:3000/; handshake failures in console.

### ISSUE THREAD

**Issue by Mocha-Bean** [justinleewells/pogo-optimizer#16]
I'm on a Linux desktop, and my phone is an Android phone.

- I have node.js, protobuf, bower, and git installed on my desktop.
- My desktop is connected to my WiFi network, and so is my phone.
- On my desktop, I installed the CA cert from 127.0.0.1:3000/ca.pem with Gnome Keyring.
- I found that my _desktop_'s internal IP was 192.168.1.144. So, I went on my _phone_ to 192.168.1.144:3000/ca.pem. I installed that certificate onto my phone.
- I then added 192.168.1.144:8081 as a proxy on my _phone_.
- On my _desktop_, I ran `$ node index` to start pogo-optimizer.
- On my phone, I opened Pokemon Go. It successfully launched.

On my desktop, in my terminal running `$ node index`, I see network activity from Pokemon Go, like
```

starting server for stats.unity3d.com
https server started for stats.unity3d.com on 37533
```

... and many others. However, I also see handshake failures like this:

```
HTTPS_CLIENT_ERROR on : Error: 140324541990720:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:s3_pkt.c:1472:SSL alert number 46
140324541990720:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:s3_pkt.c:1210:

  at Error (native)
```
And when I go to http://localhost:3000/, I see the Pokemon GO Optimizer page, so the web server works, but no Pokemon show.

![screenshot from 2016-07-19 20-05-16](https://cloud.githubusercontent.com/assets/8892160/16971734/ce536822-4deb-11e6-85a0-32f63607eccf.png)

Do I have something wrong with my certificates? Does this just not work on Android? What did I screw up?

EDIT: I can confirm that I have the egg distance glitch like many others are reporting (as well as the 5/15/16 San Francisco glitch, among other things), so at least _something_ is normal on my end.

EDIT 2: It also seems like the handshake failures in console are common, too. Maybe I'm not an edge case like I thought.

![egg glitch](http://i.imgur.com/lriImzN.png)

**Comment by justinleewells** [comment]
Can you try the new version? It will most likely fix this error.

**Comment by cardozaj** [comment]
I was having the same issue. New version worked for me. Do `git pull` to update to latest version.

**Comment by Mocha-Bean** [comment]
Now I can't log in to the game.

**Comment by artvol11** [comment]
Having exact same issue as @Mocha-Bean. Got same error, updated, now can't login to game, stuck on loading screen

**Comment by artvol11** [comment]
Also Im on a Macbook Air OSX 10.11.5

**Comment by justinleewells** [comment]
Someone else had success downgrading their version of protobuf to 2.6.1, so that's a possibility. If you just want to log in, you can turn off the proxy though.

**Comment by artvol11** [comment]
Yeah @justinleewells that was me, only fixed the install process for npm. Now that the server is up and running I am having the same issue as @Mocha-Bean

**Comment by justinleewells** [comment]
You can always turn off the proxy to log in if you can't get it working. The new version I'm working on will hopefully have fewer compatibility issues.

**Comment by artvol11** [comment]
Tried that and got back into the game, still no luck sending the data. Do you have to get a new cert each time you reboot the server?

**Comment by justinleewells** [comment]
Nah, it should just be one time.

**Comment by artvol11** [comment]
Ok, still no luck. Any ideas?

**Comment by artvol11** [comment]
It seems like the only server it won't connect to is the Niantic Pokemon go release server. That server is not showing up on my list in the terminal.

**Comment by pdavid0** [comment]
If you are on an android phone ca.pem does not work (not a supported file) I used : [DroidCert](http://www.realmb.com/droidCert/) to convert it. After that it worked like a charm !

**Comment by jnsnow** [comment]
Now in the same boat :)

Android 6.0.1, Samsung Galaxy S7
Host Machine: Fedora 24 Linux (4.6.3), nodejs 4.4.6

Seeing a lot of ssl handshake failures on various places;

https server started for android.clients.google.com on 44303
HTTPS_CLIENT_ERROR on : [Error: 139624964266048:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:s3_pkt.c:1472:SSL alert number 46
139624964266048:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:s3_pkt.c:1210:


but if I wait for most non-pogo proxy failures to pass, then reboot PoGo, I see this:

starting server for stats.unity3d.com
https server started for stats.unity3d.com on 46577
starting server for appload.ingest.crittercism.com
https server started for appload.ingest.crittercism.com on 43815
starting server for pgorelease.nianticlabs.com
https server started for pgorelease.nianticlabs.com on 33999
starting server for single.upsight-api.com
https server started for single.upsight-api.com on 40387


And then no further messages or errors, and PoGo just hangs on the Gyarados screen.

**Comment by Mession** [comment]
@jnsnow I have the same problem using a Pokemon Trainer Club account for logging in. The requests to Google services and Facebook have the ssl handshake failures. I'm on Android as well. Is there anyone who has managed to get this app working on Android?

**Comment by pdavid0** [comment]
@Mession : I did for a brief instant ... I had my full list of pokemans but as soon as I caught a new one, only this one appeared ... Maybe they changed their API ? I bet they are working hard on securing their system

**Comment by justinleewells** [comment]
@pdavid0 Nah, that's actually an error with the app. It's on the TODO list in the README. After capturing a Pokemon, it overwrites your inventory.

**Comment by jnsnow** [comment]
@Mession I did get it working after the recent update to include the newer pokemon-go-mitm module -- but I only use it like this:

(1) Enable proxy
(2) Log in to Pokemon Go, wait for pokemon list to populate.
(3) exit Pokemon go
(4) Disable proxy.

Not ideal, but it's sufficient for determining what and who to evolve.

**Comment by Mession** [comment]
@jnsnow Also got it working after the update.
