### ISSUE TITLE
npm install - fails

### ISSUE THREAD

**Issue by Un1matr1x** [justinleewells/pogo-optimizer#164]
Hi,

I'm @ Ubuntu 15.10 (GNU/Linux 4.2.0-42-generic x86_64)

and get the following error:

`user@hs:~$ git clone https://github.com/justinleewells/pogo-optimizer
Klone nach 'pogo-optimizer' ...
remote: Counting objects: 2235, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 2235 (delta 8), reused 0 (delta 0), pack-reused 2208
Empfange Objekte: 100% (2235/2235), 2.91 MiB | 1.29 MiB/s, Fertig.
Löse Unterschiede auf: 100% (638/638), Fertig.
Prüfe Konnektivität ... Fertig.
user@hs:~$ cd pogo-optimizer
user@hs:~/pogo-optimizer$ npm install
npm WARN package.json pogo-optimizer@1.3.2 No repository field.
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN engine http2@3.3.4: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! tar.unpack untar error /home/user/.npm/http-mitm-proxy/0.5.1/package.tgz
npm ERR! tar.unpack untar error /home/user/.npm/no-case/2.3.0/package.tgz
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'request/promise-core' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'request-promise'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.2.0-42-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/user/pogo-optimizer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! tar.unpack untar error /home/user/.npm/request/2.74.0/package.tgz
npm ERR! tar.unpack untar error /home/user/.npm/coffee-script/1.10.0/package.tgz
npm ERR! tar.unpack untar error /home/user/.npm/bluebird/3.4.1/package.tgz
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-protobuf@1.3.2 install /home/user/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.2.0-42-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/user/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/pogo-optimizer/npm-debug.log
npm ERR! not ok code 0
user@hs:~/pogo-optimizer$
`

**Comment by justinleewells** [comment]
Upgrade node.

**Comment by Un1matr1x** [comment]
thx- did help ...

maybe you could add an information @ readme about min versions ...
