### ISSUE TITLE
OS X EI command error （http-mitm-proxy/lib/proxy.js:62）

### ISSUE THREAD

**Issue by yy307** [justinleewells/pogo-optimizer#165]
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
Accept the cert at http://192.168.1.105:3000/ca.pem if you haven't already done so
/Users/xx/Downloads/pogo-optimizer/node_modules/http-mitm-proxy/lib/proxy.js:62
      return callback(err);
             ^
TypeError: callback is not a function

**Comment by yy307** [comment]
content of the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.3.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pogo-optimizer@1.3.2~prestart: pogo-optimizer@1.3.2
6 silly lifecycle pogo-optimizer@1.3.2~prestart: no script for prestart, continuing
7 info lifecycle pogo-optimizer@1.3.2~start: pogo-optimizer@1.3.2
8 verbose lifecycle pogo-optimizer@1.3.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle pogo-optimizer@1.3.2~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/xx/Downloads/pogo-optimizer/node_modules/.bin:/usr/local/Cellar/node/6.3.1/bin:.:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:/usr/local/cellar/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/xx/.rvm/bin:/usr/local/mysql/bin:/Users/xx/dev/maven/bin:/sbi
10 verbose lifecycle pogo-optimizer@1.3.2~start: CWD: /Users/xx/Downloads/pogo-optimizer
11 silly lifecycle pogo-optimizer@1.3.2~start: Args: [ '-c', 'gulp && node index' ]
12 silly lifecycle pogo-optimizer@1.3.2~start: Returned: code: 1  signal: null
13 info lifecycle pogo-optimizer@1.3.2~start: Failed to exec start script
14 verbose stack Error: pogo-optimizer@1.3.2 start: `gulp && node index`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid pogo-optimizer@1.3.2
16 verbose cwd /Users/xx/Downloads/pogo-optimizer
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error pogo-optimizer@1.3.2 start: `gulp && node index`
22 error Exit status 1
23 error Failed at the pogo-optimizer@1.3.2 start script 'gulp && node index'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pogo-optimizer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp && node index
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pogo-optimizer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pogo-optimizer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by cneiman** [comment]
Similar issue so I am just piggybacking here 

```
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
  at Object.exports._errnoException (util.js:860:11)
  at exports._exceptionWithHostPort (util.js:883:20)
  at Server._listen2 (net.js:1234:14)
  at listen (net.js:1270:10)
  at Server.listen (net.js:1366:5)
  at EventEmitter.listen (/Users/Chris/code/pogo-optimizer/node_modules/express/lib/application.js:617:24)
  at Object.<anonymous> (/Users/Chris/code/pogo-optimizer/index.js:122:5)
  at Module._compile (module.js:425:26)
  at Object.Module._extensions..js (module.js:432:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:457:10)
  at startup (node.js:136:18)
  at node.js:972:3
```

OSX v 10.11.6
MacBook Pro 15" early 2013
2.4GHz i7
8GB DDR3

**Comment by justinleewells** [comment]
That's not really similar, @cneiman. You already have a program listening on 3000. Either close that program or change the express port in the source.

@yy307 I'm looking into this error. There's already another issue open for it. #134

**Comment by cneiman** [comment]
Holy crap I am so sorry. I completely forgot I had gulp running in tmux

**Comment by justinleewells** [comment]
You're fine, man. No worries.
