### ISSUE TITLE
Account banned?

### ISSUE THREAD

**Issue by benjaminhallock** [justinleewells/pogo-optimizer#170]
I can't login, i get a banner telling me the service is down. I successfully ported through the proxy, got my information, then I was unable to access the server.

**Comment by benjaminhallock** [comment]
I've turned off the proxy, and logged into a different account successfully. My account gets the servers are down message.

**Comment by justinleewells** [comment]
I'm using it as we speak, so I find it unlikely.

**Comment by benjaminhallock** [comment]
Well it was true for about 5 minutes. I'm back online, but I'm scared to use it again.

**Comment by justinleewells** [comment]
I mean this is totally a "use at your own risk" program but I find it unlikely that Niantic would ban people for using it without telling me to stop development, personally.

**Comment by benjaminhallock** [comment]
Well you claim it's undetectable, so I'll assume it is. I'll just wait until they release the information in app.

**Comment by venounan** [comment]
@benjaminhallock they never released IV information in any of the other Pokemon games so I doubt they will for this one.

**Comment by clangdev** [comment]
Only thing that could happen they start something like scramblind data packets betweent client <-> server. Then it might geht pretty dark with information about IV..
Niantic must be pretty confident that the proxy you have set for your LAN is part of a "cheat". 
I doubt that this is possible.
