### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by nubs** [justinleewells/pogo-optimizer#18]
I don't see a license mentioned anywhere.  I'd suggest licensing the code so that usage/modification of the code is clear.  http://choosealicense.com/ is pretty useful for picking one.

**Comment by xenob8** [comment]
honestly licenses are viruses lol

**Comment by nubs** [comment]
@xenob8, do you mind explaining your statement?  Without a license, there are copyright issues when it comes to modifying the code.

**Comment by xenob8** [comment]
for example using a gpl license makes everyone using all or parts of the licensed code HAVE TO put it under gpl again if they want to publish it

i don't know, i just find this everything but definetly not freedom

**Comment by nubs** [comment]
GPL, as a copy-left license, definitely has some "virus"-like attributes, but can be dealt with safely and is very good for the original creator if they want to keep people from creating non-free alternatives based on their code.

A license like the MIT license is much more open to letting people do what they want with the code without any virus behavior.

So you are right that some licenses have viral components, but it's definitely not the case that they all do, and even copy-left licenses can be used in commercial products safely as long as the appropriate care is taken.

Not having a license at all means that nobody is legally allowed to distribute the code or change the code in any way without putting themselves at risk of breaking copyright law.  Just because the code is available on GitHub does not mean that it is free to use it as you see fit.  A license is there to state the conditions on how you can use it.  Without it, the code is there with "all rights reserved."

**Comment by justinleewells** [comment]
I'm just going to go with MIT. Thanks for mentioning this.
