### ISSUE TITLE
Error: Can't find module 'node forge'

### ISSUE THREAD

**Issue by Pygums** [justinleewells/pogo-optimizer#186]
![untitled](https://cloud.githubusercontent.com/assets/20668468/17239079/582a4922-552f-11e6-8a4d-8513b29f5903.png)

Not sure what to do.  Happened after i ran `git pull && npm start` start to update my version

**Comment by Pygums** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/20668468/17239242/935e54ba-5530-11e6-93aa-0cdb7cf3ac05.png)


Maybe this helps

**Comment by daveenguyen** [comment]
Maybe you don't have `node-forge` which was added to `package.json` at 1.3.0
Try running `npm install` again and see if it helps.

**Comment by oynek** [comment]
You're right. Had the same problem. Not it has been solved. Thanks.

**Comment by justinleewells** [comment]
Are you still having issues, @Pygums? Going to close this if not.

**Comment by Pygums** [comment]
Looks like `npm install` fixed it for me.  Thanks fellas.
