### ISSUE TITLE
Success on Windows 10 using virtualbox

### ISSUE THREAD

**Issue by chouhy** [justinleewells/pogo-optimizer#189]
Do everything same.
At last go to settings and change internet option from NAT to bridge

**Comment by SheepKid12** [comment]
Can confirm that this method works.

**Comment by dtandersen** [comment]
Here's a working Vagrantfile if anyone stumbles by here looking for help:

https://github.com/dtandersen/pogo-optimizer-vagrant

**Comment by justinleewells** [comment]
I'm going to close this because it's not actually an error.
