### ISSUE TITLE
Only one pokemon is showing at a time

### ISSUE THREAD

**Issue by snicker** [justinleewells/pogo-optimizer#19]
It seems that the interface is only showing the most recently captured. I cannot get it to show any existing captures.

I also have the issue with login not proceeding properly.

**Comment by snicker** [comment]
One way to get the single pokemon to update is to "edit" it's name and just press OK. It starts causing strange glitches in the game though.

**Comment by n2o** [comment]
This might come from the wrong usage of ReactJS... I will open an issue for this. There are some error messages in the JS console.

**Comment by Akokyuu** [comment]
Got the same error and some glitches like snicker mentioned. 
The console is also full of error, those are : 

`HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }`

**Comment by justinleewells** [comment]
If you capture a Pokemon, it will overwrite all previous Pokemon for the time being. After the compatibility issues, this will be a top priority.

**Comment by thrynne** [comment]
So, um, is there any way to have all the other Pokémon appear again?  I haven't managed to do so =[

**Comment by Wegi** [comment]
There is only one showing for me at all times, not only after capture. Let me know if I can provide any data for replication.

**Comment by jnsnow** [comment]
@snicker If you start the snooping AFTER login, you'll only get one pokemon as part of the delta update. Have pogo and the proxy running before you login.

@Wegi -- "only one showing" in the Pokemon Go app, or only one on the Pogo optimizer?

**Comment by Wegi** [comment]
@jsnow only one showing in the pogo-optimizer. Its possibly due to wrong rust ids set. (At least the console output suggests as much)

**Comment by justinleewells** [comment]
This was fixed in justinleewells/pogo-optimizer@65c159034bf0077072fc3c0d34aa34a9a245f8b1
