### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 46.

### ISSUE THREAD

**Issue by JawnZ** [justinleewells/pogo-optimizer#192]
I did an update of the software today, and got this error:

```
/root/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
```

I recently tweaked with my nodejs/npm for another package I was working on, but they should be the latest.

Any help is appreciated.

**Comment by justinleewells** [comment]
Delete the node_modules folder and do another `npm install`

**Comment by JawnZ** [comment]
perfect, works. thanks!
