### ISSUE TITLE
Missing folders: /public/api/pokemon and /public/assets/lib/semantic

### ISSUE THREAD

**Issue by Gokalex** [justinleewells/pogo-optimizer#2]
For the later one since its just semantic you can download it and put it in place, but for /api/pokemon that is something that should be included here, and without it i don't think that this can work

**Comment by eratio08** [comment]
the semantic entry in the bower.json is missing

**Comment by eratio08** [comment]
"/public/api/pokemon" is not a missing folder - its the api of this app - will show you an error if the inventory.json is missing

**Comment by justinleewells** [comment]
/api/pokemon is just an api endpoint, so that shouldn't require an update, but @eratio08 is correct. The semantic-ui entry was missing from the bower.json and has been added in v0.0.2. I'm closing this, but create another issue if the /public/api endpoint continues to be an issue.

**Comment by eratio08** [comment]
The Api error results from the missing inventory.json - not a real error

**Comment by justinleewells** [comment]
Perfect. We'll just assume that's solved, then.
