### ISSUE TITLE
How to uninstall image from my computer

### ISSUE THREAD

**Issue by andyshin1132** [justinleewells/pogo-optimizer#200]
Hi 
Could you teach me how to uninstall it ?
I am using ducker in win10
So I typed " docker run -d -p 3000:3000 -p 8081:8081 -it justinleewells/pogo-optimizer"
And it seems like it download about 10 file from here
but I found this computer is not using wireless so I want to uninstall it
But I don't know how 
Thanks

**Comment by justinleewells** [comment]
`docker rm $(docker ps -a -q) && docker rmi $(docker images -q)` will delete all the containers and images.

**Comment by andyshin1132** [comment]
I typed in Powershell but it seems not recognizable
+ docker rm $(docker ps -a -q) && docker rmi $(docker images -q)
+                                                ~~

Powershell cannot read  &&

    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

Don't know what to do :(
Help

**Comment by justinleewells** [comment]
Just do `rm $(docker ps -a -q)` then `rmi $(docker images -q)`

**Comment by andyshin1132** [comment]
Problem solved!
Thanks a lot!
