### ISSUE TITLE
Docker version returns random code

### ISSUE THREAD

**Issue by 93732** [justinleewells/pogo-optimizer#210]
Hi, It looks like the docker image runs fine on my setup and I can connect and look at my pokemon stats.  However, when I run the docker command, it returns a strange code.  Any idea why this code is returned? See below:

Mac-Air:~ Mac$ docker run -d -p 3000:3000 -p 8081:8081 -it justinleewells/pogo-optimizer
d121e445c4c93a6600ad531ff96d1102e05d41c958fe6501ee038721ace8792c
Mac-Air:~ Mac$

**Comment by justinleewells** [comment]
That just means that the container was started. Niantic has decided to block this app, though, so this will not work on the newest version of Pokemon GO.
