### ISSUE TITLE
Wrong usage of react-ids

### ISSUE THREAD

**Issue by n2o** [justinleewells/pogo-optimizer#22]
You're not setting the correct react-ids in your views, which causes the list to be empty or showing one item.

```bash
# localhost:3000
react.js:20209 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `PokemonList`. See https://fb.me/react-warning-keys for more information.
    in tr (created by PokemonList)
    in PokemonList (created by PokemonListContainer)
    in div (created by PokemonListContainer)
    in PokemonListContainer
```

This error mostly occurs when you are not setting a correct and unique `react-key` (or sometimes `key`) property for each item in your list. Maybe I will send you a pull request if I find the time for this in the evening.

The latest release of reactjs seems to be very fussy concerning the usage of these keys. Older versions had no problem with this.

**Comment by justinleewells** [comment]
Good catch. This project started out as a way for me to learn React, but since people actually seem to be using it, I might switch to AngularJS in the near future. Either way, I'll push a fix for this later today.

**Comment by n2o** [comment]
React.js is awesome (although I never used it directly with JavaScript, since I am a ClojureScript developer), and I have worked with Angular, but i don't like it, since it is too complicated. And the way react.js handles views is currently one of the best approaches in my opinion.

**Comment by justinleewells** [comment]
Agreed. I actually like the methodology of React a lot. I am an Angular/Node dev at work, though, and I know I'd be able to update this more frequently if I went with React.
