### ISSUE TITLE
Game freezing

### ISSUE THREAD

**Issue by Akokyuu** [justinleewells/pogo-optimizer#24]
The game is freezing when I catch a pokemon through the proxy. It's freezing aften we can see all the details and we have to click to "ok". Then we just see the background without the pokeball. 
&nbsp;

I'm running it on an iphone 6, iOS 9.3.2, the code is running on a macbook pro OSX 10.11.5. 
nmp -v : 3.9.5
node -v : 6.2.2
bower - v : 1.7.9
protobuf -v : 2.6.1

Plus, the game isn't conneting through the proxy, so connecting without it and adding it then.
At this moment, getting this errors multiple times : 

HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }

Tho, I still get updates at my localhost:3000, but only 1 pokemon in showing at a time ( #19)

**Comment by eratio08** [comment]
The freezing problem is already mention in the TODO-List of the Project
> Make client usable while catching Pokemon

**Comment by justinleewells** [comment]
Yeah, I'm going to close this. It will be fixed in a future release.

**Comment by Akokyuu** [comment]
Still have the  "Error: socket hang up"  tho....

**Comment by justinleewells** [comment]
I'm not sure what that's about. It might have to do with your downgraded version of protobuf.

**Comment by Akokyuu** [comment]
Downgraded? It's the only version brew wants to install. Seems that the 3.0 still is in beta.

**Comment by justinleewells** [comment]
That's what the --devel flag does.

**Comment by Akokyuu** [comment]
Didn't work either with proto 3.0... but finally fixed it. I have to go to safari everytime I set up the proxy and say ok to the pop up (unknown server etc). Then no more errors. And it's fixing a lot of problems.
