### ISSUE TITLE
Feature Request: Instructions for Android

### ISSUE THREAD

**Issue by jnsnow** [justinleewells/pogo-optimizer#25]
Using Fedora 24, I installed like this:

sudo dnf install nodejs protobuf protobuf-devel
sudo npm install -g bower
git clone https://github.com/justinleewells/pogo-optimizer
cd pogo-optimizer
npm install
bower install
node index

Having done that, the server is up and I installed the pem certificate on my phone. Android is warning me that a third party may be receiving traffic, so I took this to mean it's working.

Launched Pokemon Go, walked around, no pokemon show up on the intranet site. No warnings or errors on console.

Any tips or instructions for how to get this going on Android?

**Comment by Akokyuu** [comment]
You don't have to walk, you have to go in your box and open the pokemons details in order to see something.

**Comment by jnsnow** [comment]
Pulled up the box, renamed a few, no warnings, no errors in console, no pokemon in list.
Is there a verbose mode?

**Comment by artvol11** [comment]
Current experiencing a similar issue using MacOSX El Capitan and an iPhone 5c running 9.3.2.

**Comment by eratio08** [comment]
have you set the server as a proxy on your phones wifi?

**Comment by jnsnow** [comment]
Oh, you know, no. It was missing from the instructions in the README. :o)
Any recommendations for how to do that on Android? (Or IOS for that matter, as the README doesn't explain how.)

**Comment by eratio08** [comment]
On iOS you go to wifi and tap on the "i" icon at the and of the row of your currently connected wifi.
You scroll down till you see the proxy setting.
Select manual configuration and write the ip of your proxy and the port 8081.

should work similar on android

**Comment by artvol11** [comment]
I set the proxy and still am not receiving any data

**Comment by eratio08** [comment]
restart kill pokemon go and restart the app while connected to the proxy. The terminal will show you some new lines if it works

**Comment by pdavid0** [comment]
If you are on an android phone ca.pem does not work (not a supported file) I used : [DroidCert](http://www.realmb.com/droidCert/) to convert it. After that it worked like a charm !

**Comment by jnsnow** [comment]
For me, I didn't have a problem installing ca.pem; when you say it "doesn't work" do you mean you installed it and nothing happened, or you weren't able to install it?

Samsung Galaxy S7, Android 6.0.1.

@pdavid0 -- I assume you also had to set up a proxy too, though, right?

**Comment by artvol11** [comment]
@eratio08 when i do that the app wont load at all

**Comment by eratio08** [comment]
@artvol11 had connection problems myself - I removed the node modules folder and did a clean `npm install` - did the job for me (also check if the proxy setting are correct)

**Comment by artvol11** [comment]
clean npm install fixed socket error, but now the data is not loading into the localhost:3000

**Comment by pdavid0** [comment]
@jnsnow Yes, I used the Proxy .

What I mean is that When you go in Setting > Security > Install From Storage

You can't install the ca.pem file you just downloaded, you have to convert it. Without that extra step I could not use pogo-optimizer.

**Comment by jnsnow** [comment]
@pdavid0 -- Yes, downloading the pem works just fine (it saves it to "My Files" on Android 6.0.1 @ S7) and then if you "open" the file, it offers to install it. Seems to work out OK in that regard.

For the proxy, are you using the native android proxy that you can access via the WiFi menu? I'm not having luck with that [here at work] but I will attempt to re-try it when I get home.

I'll send a PR with better instructions for Linux (hosts) and Android (devices) if/when I get it all working, with screenshots, etc.

**Comment by jnsnow** [comment]
Alright, the README has been updated a bit with some Fedora/Android instructions; closing this issue. Open new bugs for specific server issues!

**Comment by jnsnow** [comment]
@pdavid0  Hmm, unfortunately I don't know where else to reply, but now that I've got the proxy running, I have the same handshake issue as everyone else. pem was definitely installed, proxy is definitely active, but can't defeat the login screen, the toughest gym trainer of them all.

**Comment by pdavid0** [comment]
@jnsnow Yes to all your questions.
