### ISSUE TITLE
Client starts pogorelease server, then nothing happens

### ISSUE THREAD

**Issue by artvol11** [justinleewells/pogo-optimizer#27]
I get this output, running on a Macbook Air OSX El Capitan, and IOS 9.

Austins-MacBook-Air:pogo-optimizer austinturner$ node index
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
Accept the cert at 192.168.0.7:3000/ca.pem if you haven't already done so
starting server for p36-keyvalueservice.icloud.com
https server started for p36-keyvalueservice.icloud.com on 60545
starting server for appload.ingest.crittercism.com
https server started for appload.ingest.crittercism.com on 60807
starting server for p53-buy.itunes.apple.com
https server started for p53-buy.itunes.apple.com on 60809
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }
**starting server for pgorelease.nianticlabs.com
https server started for pgorelease.nianticlabs.com on 61070**
starting server for api.foursquare.com
https server started for api.foursquare.com on 62280
starting server for gs-loc.apple.com
https server started for gs-loc.apple.com on 62489

It starts the server, but then nothing happens.

**Comment by artvol11** [comment]
Now this error occurs

HTTPS_CLIENT_ERROR on : Error: 140735168552960:error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request:../deps/openssl/openssl/ssl/s23_srvr.c:394:

  at Error (native)

**Comment by justinleewells** [comment]
Are you using Android or iOS?

**Comment by artvol11** [comment]
iOS

**Comment by artvol11** [comment]
> I get this output, running on a Macbook Air OSX El Capitan, and IOS 9.

**Comment by justinleewells** [comment]
It looks like the error is only happening with the itunes server. Is the app working correctly outside of that error?

**Comment by justinleewells** [comment]
So you can't log in? There isn't supposed to be anything in the console. You are just supposed to go to localhost:3000 after logging into the app.

**Comment by artvol11** [comment]
Nothing shows up there either

**Comment by justinleewells** [comment]
Any errors in the web console?

**Comment by artvol11** [comment]
no, but now I'm getting this error

starting server for pgorelease.nianticlabs.com
https server started for pgorelease.nianticlabs.com on 52786
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }

**Comment by artvol11** [comment]
This error appears to be in a constant loop

**Comment by artvol11** [comment]
tried upgrading protobuf, still getting the same error

**Comment by artvol11** [comment]
clean npm install fixed socket error, but now the data is not loading into the localhost:3000

**Comment by brutalgg** [comment]
I am having a similar issue with my Macbook Air and iPhone. I can load into the game and traffic goes through but i get a error when clicking on pokemon in my storage as well as nothing loading in the web UI. Its just a red background. One error is connection reset and the other is a Proxy to server error.

**Comment by justinleewells** [comment]
Could you guys try again with the newest version?

**Comment by brutalgg** [comment]
Just re-cloned. Error Persists. Just some output from the console to help maybe pin point.
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
Accept the cert at 10.10.30.13:3000/ca.pem if you haven't already done so
starting server for bootstrap.upsight-api.com
starting server for appload.ingest.crittercism.com
https server started for bootstrap.upsight-api.com on 49622
https server started for appload.ingest.crittercism.com on 49623
starting server for pgorelease.nianticlabs.com
https server started for pgorelease.nianticlabs.com on 49624
starting server for single.upsight-api.com
https server started for single.upsight-api.com on 49628
starting server for batch.upsight-api.com
https server started for batch.upsight-api.com on 49634
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }
PROXY_TO_SERVER_REQUEST_ERROR on /batch/v1/fc708d6b22bf4994acdf28d0511acc2d/: { Error: getaddrinfo ENOTFOUND batch.upsight-api.com batch.upsight-api.com:443
  at errnoException (dns.js:28:10)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)

  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'batch.upsight-api.com',
  host: 'batch.upsight-api.com',
  port: 443 }

Everything starts fine the Errors start when i attempt to view a Pokemon. Also the webpage is just purely red. I don't even see the menu bar assets with no pokemon as someone else had mentioned.

**Comment by brutalgg** [comment]
Is there a error log per chance that i could check for the webpage why the web assets aren't loading?

**Comment by quincygogo** [comment]
I'm having similar issues. Can anyone please help?

**Comment by brutalgg** [comment]
I was able to get it running by restarting the process. I think i missed the bower install previously.
