### ISSUE TITLE
/data/inventory.json missing

### ISSUE THREAD

**Issue by Bitti09** [justinleewells/pogo-optimizer#3]
Getting  this error spam  in console:

"Error: ENOENT: no such file or directory, open './data/inventory.json'
  at Error (native)

Error: ENOENT: no such file or directory, open './data/inventory.json'
  at Error (native)"

**Comment by eratio08** [comment]
You have to install the Man-in-the-middle cert on your phone first so that the server can catch the inventory json

**Comment by TwilightWinter** [comment]
I've installed the MITM certificate, I have the warning ('A third party may be monitoring your connection') so I know it's installed, but I'm still getting a spam of the error above.

**Comment by eratio08** [comment]
Should work, this app uses https://github.com/rastapasta/pokemon-go-mitm-node
The instructions there say exactly what you did.

Can't get the inventory myself...

**Comment by Gokalex** [comment]
@eratio08 did you get the other one (  https://github.com/rastapasta/pokemon-go-mitm-node ) to work?

**Comment by justinleewells** [comment]
Sorry, guys. I got this working at 2am last night and I'm uninstalling all the dependencies and building it from scratch. I'll update with a new version/README ASAP.

**Comment by eratio08** [comment]
Well, no didn't try it. This app uses the MITM-Node.
The unstructions there say that you have to connect to your MITM server to use it as a proxy

**Comment by Gokalex** [comment]
@eratio08 That did the trick! Thanks!

**Comment by justinleewells** [comment]
I added in some error handling for no inventory.json existing in v0.0.2. Should no longer be getting spammed with the inventory.json message. I'll update the README to reflect adding the mitm as a proxy though.
