### ISSUE TITLE
Google unable to login

### ISSUE THREAD

**Issue by einstein95** [justinleewells/pogo-optimizer#34]
I've followed the instructions (converted the ca.pem to crt using OpenSSL in order to install it on my Android phone) and it works until it gets to the logging in part:
```
starting server for android.clients.google.com
https server started for android.clients.google.com on 37437
HTTPS_CLIENT_ERROR on : Error: 140371090372416:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:s3_pkt.c:1472:SSL alert number 46
140371090372416:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:s3_pkt.c:1210:

  at Error (native)

HTTPS_CLIENT_ERROR on : Error: 140371090372416:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:s3_pkt.c:1472:SSL alert number 46
140371090372416:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:s3_pkt.c:1210:

  at Error (native)
```
I am running the latest commit as of 6715ae7f704df920d5cd433d96a7895ba13b4601. If there's anything else needed, I'll be glad to help.

**Comment by jnsnow** [comment]
Try the newest commit: https://github.com/justinleewells/pogo-optimizer/commit/8c81cfda26af34a14b33e83091c8970eb55bd549

There's a new MITM helper library that resolved some issues for me on Android.

I'm node a node guy so I dunno if you have to reinitialize the package or what.

**Comment by nubs** [comment]
> I'm node a node guy so I dunno if you have to reinitialize the package or what.

After updating the source, you'll need to rerun `npm install` to fetch the updated dependencies.

**Comment by einstein95** [comment]
Yep, that solved it. Thanks!
