### ISSUE TITLE
Only Red Background : VM Debian 8

### ISSUE THREAD

**Issue by Guiver** [justinleewells/pogo-optimizer#41]
Hello,
(sorry for my English)
Install seems correct but I have only a red background on the web page, I haven't any data or image.
I haven't GUI on my pogo-optimizer server, I try to access the webserver with another PC on the same network (pogo.serveur.ip:3000).

Any idea for see my data ?
How can I read any log ? (I never use node)
How can I update pogo-optimizer ? (git pull | npm install It's OK ?)
I need to install certificate on debian too ? on the PC who tried to load the Web Page ?

**My environment :**
Windows 7 X64 as host (vmware workstation 12 player)
**Virtual Machine / pogo-optimizer server :**
Debian 8 x64 (without desktop)
**Smartphone :**
Android KitKat
Pokemon Go 0.2.9.3 (tested with 0.2.9.2 too).

Here, all my step for the server install 

> apt-get install -y curl build-essential libprotobuf-dev git pkg-config
> curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
> apt-get install nodejs
> npm install -g bower
> git clone https://github.com/justinleewells/pogo-optimizer
> npm install
> node index
Response :
> [+++] PokemonGo MITM Proxy listening on 8081
> [!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
> Pokemon GO Optimizer front-end listening on port 3000
> Accept the cert at 127.0.1.1:3000/ca.pem if you haven't already done so

I configure proxy on the phone and install ca.pem.
Pokemon Go still work, I can caught Pokemon or open my inventory.
Some minor bug :
- My pokemon name are in English (usually French).
- Pokemon 3D sprite didn't load normally, I can see it by swipping left.
- Map : San Francisco, USA May 15, 2016
- Egg are 0.0/0.0

Here node return after pokemon Go launch (google account) :
> starting server for stats.unity3d.com
> https server started for stats.unity3d.com on 53712
> starting server for batch.upsight-api.com
> https server started for batch.upsight-api.com on 46040
> starting server for appload.ingest.crittercism.com
> https server started for appload.ingest.crittercism.com on 40625
> starting server for pgorelease.nianticlabs.com
> https server started for pgorelease.nianticlabs.com on 39309
> starting server for android.clients.google.com
> https server started for android.clients.google.com on 39633
> starting server for single.upsight-api.com
> https server started for single.upsight-api.com on 36147
> starting server for play.googleapis.com
> https server started for play.googleapis.com on 36167
> starting server for www.google.com
> https server started for www.google.com on 53871

Thanks you

**Comment by derekhh** [comment]
I'm seeing the same issue.

**Comment by farkam135** [comment]
Run

bower install

**Comment by derekhh** [comment]
Issue solved. Thanks! :)

**Comment by Guiver** [comment]
Issue solved too,Thanks you !
Here all step for a fresh Debian 8 minimal install :

> apt-get install -y curl build-essential libprotobuf-dev git pkg-config
> curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
> apt-get install nodejs
> npm install -g bower
> git clone https://github.com/justinleewells/pogo-optimizer
> cd pogo-optimizer
> npm install
> bower install --allow-root
> node index
