### ISSUE TITLE
Resetting the data

### ISSUE THREAD

**Issue by crimes86** [justinleewells/pogo-optimizer#42]
I imported my pokemon to the optimizer app, transferred all the weak ones, and then went out to catch a bunch more.  What is the most efficient way to reset the data so I can get a fresh import that doesn't have all the old pokemon I transferred still stored in the server?

**Comment by justinleewells** [comment]
It currently overwrites the inventory each time you log in. I have changes planned for this in the future.

**Comment by crimes86** [comment]
Oh ok so it already refreshes the data each time..  that is what I hoped for anyways.  I just couldn't tell if there was duplicate data or not.  Thanks for the quick reply!
