### ISSUE TITLE
npm install -g bower error

### ISSUE THREAD

**Issue by danieledifice** [justinleewells/pogo-optimizer#49]
Daniels-MacBook-Pro:~ danielroymond$ npm install -g bower
npm ERR! tar.unpack untar error /Users/danielroymond/.npm/bower/1.7.9/package.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path /usr/local/lib/node_modules/bower
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/bower'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/bower']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/bower',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/bower',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danielroymond/npm-debug.log

sorry, I'm n00b using this, whats wrong with my npm install?

**Comment by danieledifice** [comment]
I try LIBPROTOBUF=/usr/local/lib/protobuf npm install node-protobuf but getting this error:

Daniels-MacBook-Pro:~ danielroymond$ LIBPROTOBUF=/usr/local/lib/protobuf npm install node-protobuf
-
> node-protobuf@1.3.2 install /Users/danielroymond/node_modules/node-protobuf
> node-gyp rebuild

  CXX(target) Release/obj.target/protobuf/src/init.o
In file included from ../src/init.cpp:1:
../src/common.h:11:10: fatal error: 'google/protobuf/descriptor.h' file not
      found
#include <google/protobuf/descriptor.h>
         ^
1 error generated.
make: *** [Release/obj.target/protobuf/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/danielroymond/node_modules/node-protobuf
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-protobuf"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-protobuf@1.3.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danielroymond/npm-debug.log
Daniels-MacBook-Pro:~ danielroymond$ Daniels-MacBook-Pro:~ danielroymond$ LIBPROTOBUF=/usr/local/lib/protobuf npm install node-protobuf
-bash: Daniels-MacBook-Pro:~: command not found
Daniels-MacBook-Pro:~ danielroymond$ -
-bash: -: command not found
Daniels-MacBook-Pro:~ danielroymond$ > node-protobuf@1.3.2 install /Users/danielroymond/node_modules/node-protobuf
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Daniels-MacBook-Pro:~ danielroymond$ > node-gyp rebuild
-bash: rebuild: command not found

**Comment by justinleewells** [comment]
`sudo npm install -g bower`

**Comment by danieledifice** [comment]
solved, thanks a lot 👍
