### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by xenob8** [justinleewells/pogo-optimizer#5]
menaged to install all the dipendences and everything
i get this syntax error tho

/home/xb8/pkgo/pogo-optimizer/node_modules/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/middleware/wildcard.js:8
const HOSTNAME_REGEX = /^(.+)(\.[^\.]{4,}(\.[^\.]{1,3})*\.[^\.]+)$/;
^^^^^
SyntaxError: Use of const in strict mode.

**Comment by kepakiano** [comment]
What version of nodejs are you using? (node -v)

**Comment by xenob8** [comment]
node is v0.10.25
i just saw the script got updated and i was installing the older version so i clonet the new git and retried installing and now when duing node index i get this error:

module.js:340
    throw err;
          ^
Error: Cannot find module 'pokemon-go-mitm-node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/xb8/pkgo/pogonew/pogo-optimizer/index.js:40:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by eratio08** [comment]
try updating node to v6.3.0 and npm install

**Comment by xenob8** [comment]
oh gawd. and it says it is last version ._.

**Comment by xenob8** [comment]
well i updated it but the error remains, i think it is a broken link to the mitm module

**Comment by eratio08** [comment]
do you get the protobuf error?

**Comment by xenob8** [comment]
protobuf is correctly installated

**Comment by eratio08** [comment]
Try to` npm install pokemon-go-mitm-node` in the project folder

**Comment by xenob8** [comment]
npm is last version
npm install pokemon-go-mitm-node did not solve the problem

**Comment by justinleewells** [comment]
I just updated the dependency. The owner of the pokemon-go-mitm-node repo changed the package.json and it broke the npm install. Should be good to go now. Once they get it added to npm I'll use that so we don't have this problem in the future.
