### ISSUE TITLE
Unable to start pokemon go

### ISSUE THREAD

**Issue by mrawesome1337** [justinleewells/pogo-optimizer#51]
Ok so I have made some progress on getting this setup on windows using docker.

Docker starts a virtualbox VM automagically. I have NAT connection setup. I port forwarded 8081 and 3000. I was able to access the web page and download the cert on my phone using my windows IP address. Yay!

I installed the cert on my android device and started up pokemon go. "Failed to get player information from the server." I grabbed the logs from the docker container running pogo and they are pasted below. My next step will be reinstalling the container. It looks like there have been a few updates, but I think I missing something.

[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
Accept the cert at 172.17.0.2:3000/ca.pem if you haven't already done so
starting server for clients4.google.com
https server started for clients4.google.com on 45875
starting server for samsungbuiasr.vlingo.com
https server started for samsungbuiasr.vlingo.com on 41431
starting server for www.googleapis.com
https server started for www.googleapis.com on 36679
HTTPS_CLIENT_ERROR on : Error: 140107865659200:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 46
140107865659200:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1210:

  at Error (native)

starting server for stats.unity3d.com
https server started for stats.unity3d.com on 38202
PROXY_TO_SERVER_REQUEST_ERROR on /voicepad/lmtt: { Error: socket hang up
  at createHangUpError (_http_client.js:252:15)
  at TLSSocket.socketOnEnd (_http_client.js:344:23)
  at emitNone (events.js:91:20)
  at TLSSocket.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:973:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
 code: 'ECONNRESET' }
starting server for appload.ingest.crittercism.com
https server started for appload.ingest.crittercism.com on 37342
starting server for pgorelease.nianticlabs.com
https server started for pgorelease.nianticlabs.com on 32944
starting server for android.clients.google.com
https server started for android.clients.google.com on 45142
starting server for single.upsight-api.com
https server started for single.upsight-api.com on 46362
starting server for api.crittercism.com
https server started for api.crittercism.com on 32896
starting server for graph.facebook.com
https server started for graph.facebook.com on 34527
starting server for settings.crashlytics.com
https server started for settings.crashlytics.com on 32908
starting server for kinesis.us-east-1.amazonaws.com
https server started for kinesis.us-east-1.amazonaws.com on 40111
starting server for www.google.com
https server started for www.google.com on 39494
PROXY_TO_SERVER_REQUEST_ERROR on /voicepad/lmtt: { Error: socket hang up
  at createHangUpError (_http_client.js:252:15)
  at TLSSocket.socketOnEnd (_http_client.js:344:23)
  at emitNone (events.js:91:20)
  at TLSSocket.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:973:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
 code: 'ECONNRESET' }
starting server for batch.upsight-api.com
https server started for batch.upsight-api.com on 36034
starting server for bootstrap.upsight-api.com
https server started for bootstrap.upsight-api.com on 42892
PROXY_TO_SERVER_REQUEST_ERROR on /voicepad/lmtt: { Error: socket hang up
  at createHangUpError (_http_client.js:252:15)
  at TLSSocket.socketOnEnd (_http_client.js:344:23)
  at emitNone (events.js:91:20)
  at TLSSocket.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:973:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
 code: 'ECONNRESET' }

**Comment by justinleewells** [comment]
I'm not sure when you built the container, but I would definitely pull it if it wasn't today. The updates I pushed last night were pretty big and probably fix this issue.

**Comment by mrawesome1337** [comment]
Sorry for wasting your time. I updated it works perfect. Thank you very much.
