### ISSUE TITLE
SyntaxError: const in strict mode

### ISSUE THREAD

**Issue by dumit** [justinleewells/pogo-optimizer#58]
Prevents server from launching (MacOSX 10.11)

$ node index
/Users/user1/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/http-mitm-proxy/lib/middleware/wildcard.js:8
const HOSTNAME_REGEX = /^(.+)(\.[^\.]{4,}(\.[^\.]{1,3})*\.[^\.]+)$/;
^^^^^
SyntaxError: Use of const in strict mode.

**Comment by justinleewells** [comment]
Upgrade your node version.

**Comment by dumit** [comment]
Sweet! That plus then upgrading protobuf did it!
