### ISSUE TITLE
Pokémon List almost empty, no eggs

### ISSUE THREAD

**Issue by kepakiano** [justinleewells/pogo-optimizer#6]
When the webserver is running and the proxy is set on my phone some weird things happen in Pokémon Go: All my eggs and Pokémon are gone except a Weedle which costs 1200 Candy to evolve and it says it was caught on the 15th of May in San Francisco... wth. Diary, Candy count, star dust, favourites (this weedle was faved) and spawning Pokémon seem to be unaffected. The list under localhost:3000 is empty as well.
The issue goes away if I stop the webserver and restart the app.

The console output is clean except:
HTTPS_CLIENT_ERROR on : Error: 140305006872448:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 46
140305006872448:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1210:

  at Error (native)

Specs: Android 5.1/6.0.1 and Ubuntu 14.04

**Comment by andrewda** [comment]
This happened to me too. There was one Pokemon in the app and no eggs, despite having 100+ Pokemon and 9 eggs while not connected to the webserver.

**Comment by andrewda** [comment]
Fixed in https://github.com/justinleewells/pogo-optimizer/commit/e08fdb9196104d1feb53a2eea38a992d63228c50

**Comment by kepakiano** [comment]
Not for me, same error still present after pulling head.

**Comment by justinleewells** [comment]
As soon as you log in or after catching a Pokemon? After catching a Pokemon is a different error that I need to work on.

**Comment by kepakiano** [comment]
As soon as I log in.

**Comment by xenob8** [comment]
it seems i have the same problem now

**Comment by queso** [comment]
I turned on `debug: true` for the mitm proxy and I am seeing this in the logs:

```
[+] Response for action GetInventory
{ success: true,
  inventory_delta:
   { original_timestamp_ms: '1468961850688',
     new_timestamp_ms: '1468961850688',
     inventory_items: [] } }
[!] Overwriting GetInventory
```

**Comment by queso** [comment]
I've opened an issue here: https://github.com/rastapasta/pokemon-go-mitm-node/issues/4

**Comment by queso** [comment]
Looks to be an issue with expecting data via the GetInventory call, which only gives us changes since last timestamp.

**Comment by queso** [comment]
Ok, a lot more poking around and I've at least got the list populating now for the app. The game still only shows one pokemon when it works...

It seems the API is changing or perhaps the mitm is changing the return values.

**Comment by timwah** [comment]
PR #17 should at least address the inventory being partially or completely empty by unsetting the `last_timestamp_ms` of the GetInventory call.

**Comment by jnsnow** [comment]
@kepakiano can you update to the latest git commit, re-run the installation commands, and verify that this is either fixed or is still a problem?
