### ISSUE TITLE
Pokemon Detail view error

### ISSUE THREAD

**Issue by toryxxxx** [justinleewells/pogo-optimizer#61]
When I connect the pgog- optimizer server which I put in my mac and start to play, all of my Pokemon Detail page seem to be wrong, I can't see the right data and use the function in that page.

**Comment by toryxxxx** [comment]
![img_0076](https://cloud.githubusercontent.com/assets/20598346/17076781/a19fd5e0-50ed-11e6-8139-75632c5877fd.PNG)
![img_0077](https://cloud.githubusercontent.com/assets/20598346/17076784/aabe6448-50ed-11e6-80e4-baf005ebbd4a.PNG)

**Comment by esfomeado** [comment]
It's a know issue mainly due some wrong protobuf files.

**Comment by toryxxxx** [comment]
any plan to solve the problem？：）

**Comment by esfomeado** [comment]
@toryxxxx You can make this change that i mention on this pull request:
https://github.com/justinleewells/pogo-optimizer/pull/63/files

And reinstall pogo-optimized (Delete node_modules folder and do npm install again)

This will only solve a few problems. We have to wait for the guys from protobuf team solves this.

**Comment by Shauneh** [comment]
You don't need to be constantly connected to get the information you need, it's easier just to disable the proxy once you have uploaded your data and then go catch more pokemon and do a mass release, but as @esfomeado says if you grab his change you will always have the latest version of the mitm project used in the project.

**Comment by toryxxxx** [comment]
thank you~ @Shauneh @esfomeado

**Comment by justinleewells** [comment]
I believe this is fixed in the newest version. Feel free to re-open if I'm wrong.
