### ISSUE TITLE
Problem with Docker & Windows 7

### ISSUE THREAD

**Issue by qwer4790** [justinleewells/pogo-optimizer#64]
I successfully build it in Docker, but Dock use the ip :192.168.99.100 instead of localhost, thus the container uses 192.168.99.100:3000 and 8081.
(I can visit 192:168.99.100:3000 to see a page of  pogo-optimizer but no pokemon data recorded, and localhost:3000 is not working)

Then I set proxy on my iPhone to 192.168.99.100:8081 but it had no internet connection after setting the proxy

**Comment by weblack** [comment]
mgxts on reddit posted awesome instructions for windows users! I suggested he bring them over to the readme on this repo. I had the docker and cert working but like you, was restricted by the 192.168.99.100 IP address. The netsh commands cleared that up. I've put a link below for now. 

https://www.reddit.com/r/TheSilphRoad/comments/4tk33a/pokemon_go_optimizer_automatically_detect_pokemon/d5nyshi

**Comment by qwer4790** [comment]
I did what that link said, but still can't get proxy working. How did you set up your phone? (ios)

**Comment by weblack** [comment]
I used my computers actual local IP not the one provided by docker.

I also needed to follow the provided instructions on converting the cert file to a .crt and transfer that to my phone and install. To make sure you phone is connected, you should be able to access the .pem cert file. If you can access that and you can login to the app, your phone should be set up I believe.

**Comment by qwer4790** [comment]
I tried both 192.168.99.100:8081 and localhost(which is 127.0.0.1), none worked. I can't access the crt page so I can not download ca.pem (actually I have no internet connection after setting the proxy). BTW, I am using unrooted iphone, that conversion is for Andriod right?

**Comment by justinleewells** [comment]
Okay, so you cannot visit localhost on your phone. If the computer's ip address is 192.168.99.100, then you need to put 192.168.99.100 as the proxy ip and 8081 as the proxy port in your phone. This means that you need to visit 192.168.99.100:3000/ca.pem to install the cert on your iPhone. Be sure to use Safari.

**Comment by qwer4790** [comment]
Hi, thx for reply, My computer's localhost is 192.168.0.102, that 192.168.99.100 is docker machine's ip. I am not sure which to use. I will try later when I back to home.

**Comment by justinleewells** [comment]
Use 192.168.0.102.

**Comment by qwer4790** [comment]
Got it! It works! Thank you all of you guys. You make my day

**Comment by justinleewells** [comment]
Awesome! Glad you got it working!
