### ISSUE TITLE
Is (ATK + DEF + STA) / 45 the best calculation?

### ISSUE THREAD

**Issue by joshmadewell** [justinleewells/pogo-optimizer#76]
I could be wrong here but wouldn't:

`(ATK/15) * (DEF/15) * (STA/15)` be a better calculation to determine if a pokemon is "perfect"?

**Comment by justinleewells** [comment]
Yes, it's the best for determining perfect IVs.

**Comment by nubs** [comment]
`(ATK/15) * (DEF/15) * (STA/15)` with stats `15/15/0` would end up giving you a 0.  That doesn't seem nearly as useful as `(ATK + DEF + STA) / 45` which gives you 2/3.

**Comment by joshmadewell** [comment]
@nubs Yeah, I had a complete brain fart for some reason when I posted this. I was thinking that you'd rather have a pokemon with >0 in all three stats but that's just silly, this calculation is the best one, no doubt.
