### ISSUE TITLE
Gray Color Scheme v1.0.0 is less functional

### ISSUE THREAD

**Issue by Scott05** [justinleewells/pogo-optimizer#77]
Thanks for all your work on this, but I wanted to request that the previous color variances on the spreadsheet in the previous versions be brought back. The different colors relating to type made the list much easier to read and follow along across the multiple columns. Now with it all being a dark gray it is much harder to follow. Thanks!

**Comment by justinleewells** [comment]
I noticed that too! I'm working on a fix right now.

**Comment by justinleewells** [comment]
Check out the newest release and tell me what you think.
