### ISSUE TITLE
pokemon go fails to login

### ISSUE THREAD

**Issue by xenob8** [justinleewells/pogo-optimizer#8]
everything is up and running but if i try to log in pokemon go it fails to do so 
(if i stop the prosy server it connects correctly tho)

**Comment by justinleewells** [comment]
It was temporarily not working for me as well, but it seems to be working fine atm. Mind giving it another try?

**Comment by queso** [comment]
I am getting the same, first time trying to use it after pulling master.

**Comment by justinleewells** [comment]
Are you both on Windows? This doesn't seem to be an issue on OSX.

**Comment by xenob8** [comment]
Ubuntu 14.04.4 LTS

**Comment by queso** [comment]
I am on OSX. Haven't used Windows in years.

**Comment by queso** [comment]
@justinleewells any ideas? Not sure where to start debugging this.

**Comment by justinleewells** [comment]
I'm honestly not sure. I just upgraded the mitm version. Maybe try that? It seems like an issue with the POGOProtos, which is what they updated.

**Comment by xenob8** [comment]
now it logs but on the node app there are no pokemon displayed

**Comment by queso** [comment]
Same here, just cleared out my node_modules folder and updated the app, re-ran `npm install` and got everything up to date. The app will login and work now, but I am not seeing any pokemon in the node app.

**Comment by nubs** [comment]
I've updated to the newest version.  It still seems to have trouble logging in.  I don't have any more information to share yet other than to say that something still isn't working 100% properly.  I see standard log messages about starting servers for various domains.  I'm going to keep debugging later

**Comment by nubs** [comment]
Turning on mitm debug I get this output snippet:
```
starting server for pgorelease.nianticlabs.com
https server started for pgorelease.nianticlabs.com on 33697
[+++] Request to /plfe/rpc
[+] Request for action GetPlayer: 
{}
[+] Request for action GetHatchedEggs: 
{}
[+] Request for action GetInventory: 
{}
[!] Overwriting POGOProtos.Networking.Requests.Messages.GetInventoryMessage
[+] Request for action CheckAwardedBadges: 
{}
[+] Request for action DownloadSettings: 
{}
[+] Waiting for response...
```

and then nothing seems to progress.  I'm not sure exactly where to go from here but I'll try some more tomorrow.

**Comment by n2o** [comment]
I am having the same issue. It works when I first login to the app and then switch to my WIFI connection. I am on Arch Linux x64, but have installed everything in a clean Debian environment using Docker (see PR #21)

**Comment by numbers1311407** [comment]
Getting the same result as @nubs, and same output from the server after turning on debug to the MITM instance.

Login hangs and eventually fails.

**Comment by nubs** [comment]
I was able to get things working kinda after making a few changes.  I logged into pokemon go over 4g, then once I was logged in I switched over to the wifi with proxy.  That still only fetched one pokemon at a time and was kind of buggy, so I made a change to the node.js code to set the date for the inventory delta request back a bit (`data.last_timestamp_ms = data.last_timestamp_ms - 1000000000`).  That finally got me a useful inventory dump that I could use.

**Comment by numbers1311407** [comment]
It actually worked for me after removing the request handler (which deletes the `last_timestamp_ms` altogether).  Login was fine, full inventory was returned.  I don't know enough about the code to know why the timestamp should be deleted on the first request though.

**Comment by thrynne** [comment]
could you share a bit more about what you did to get a full inventory?

**Comment by numbers1311407** [comment]
If you're having the same problem as me, I just opened up the `index.js` and commented out the request handler, lines 49-55.  I do not however know the reasoning behind deleting the timestamp from the first request nor the consequences of removing the handler and not doing so.

**Comment by thrynne** [comment]
That didn't work for me=[  I guess I'm having some other problem.

**Comment by ShadowDrgn** [comment]
That worked for me too actually.
