### ISSUE TITLE
OSX Setup failed.

### ISSUE THREAD

**Issue by autumnqiuji** [justinleewells/pogo-optimizer#80]
Hello! 
I followed the guide on OSX, but after command ”npm install” there are lots of errors.
<img width="1059" alt="screen shot 2016-07-24 at 4 23 08 pm" src="https://cloud.githubusercontent.com/assets/6902512/17082774/1e7c858a-51bc-11e6-8e97-88d379e50ca1.png">
<img width="774" alt="screen shot 2016-07-24 at 4 23 43 pm" src="https://cloud.githubusercontent.com/assets/6902512/17082775/1f4b7ef8-51bc-11e6-9968-cdccc265b016.png">
“bower install” is ok.

**Comment by autumnqiuji** [comment]
“npm start” is also has errors.
It seems cannot find ‘pokemon-go-mitm’ module, but i can find it in my filesystem.
<img width="690" alt="screen shot 2016-07-24 at 4 27 44 pm" src="https://cloud.githubusercontent.com/assets/6902512/17082777/1f53d724-51bc-11e6-9226-f405ba610829.png”>
<img width="1103" alt="screen shot 2016-07-24 at 4 28 44 pm" src="https://cloud.githubusercontent.com/assets/6902512/17082776/1f532a40-51bc-11e6-9a4d-10be25d7eb66.png”>
Should i install some dependent libraries first?
Thanks for the awesome work!

**Comment by justinleewells** [comment]
What version of protoc do you have installed? And did you try `npm install pokemon-go-mitm`?

**Comment by autumnqiuji** [comment]
It’s protobuf-3.0.0-beta-4.
And i tried install pokemon-go-mitm:
<img width="938" alt="screen shot 2016-07-24 at 5 02 51 pm" src="https://cloud.githubusercontent.com/assets/6902512/17082929/1d12ccfe-51c1-11e6-9cac-d683a9038bbf.png">

**Comment by justinleewells** [comment]
Maybe try removing the node_modules folder and trying again. Anyone else have any ideas?

**Comment by autumnqiuji** [comment]
Finally succeeded!
Just close the proxy!
Thank you very much!

**Comment by justinleewells** [comment]
You're welcome! Have fun!
