### ISSUE TITLE
Where do i find the new Move generation utility?

### ISSUE THREAD

**Issue by 93732** [justinleewells/pogo-optimizer#81]
Where do i find the new Move generation utility?

**Comment by justinleewells** [comment]
The move generation utility just generated a database. I'll be adding an "optimal moves" feature in the near future.

**Comment by Shauneh** [comment]
Optimal Moves would be good as maybe a percentage of maximum DPS output?

Just a thought to help you code it!

**Comment by justinleewells** [comment]
Whenever I add optimal moves, I'll add sorting by DPS as well. The Pokemon database doesn't have the possible moves entered right now, so I'll have to do that by hand. I've just been putting it off since it's going to be rather time consuming.
