### ISSUE TITLE
Cannot connect via a different computer.

### ISSUE THREAD

**Issue by 93732** [justinleewells/pogo-optimizer#82]
I can see the spreadsheet when accessing on the same computer as the pogo optimizer server.  However when I switch to a different computer (on the same LAN) as the pogo optimizer server, I can only reach the connect screen.  With version 0.1.0, it worked fine from any computer connected to the LAN.

**Comment by justinleewells** [comment]
This commit should fix it justinleewells/pogo-optimized@bf37c04
