### ISSUE TITLE
Allow for secondary and tertiary sorting in the spreadsheet

### ISSUE THREAD

**Issue by Orkeren** [justinleewells/pogo-optimizer#84]
The title basically says it all. It would be awesome if I could fx could sort first by level, then by IV% and lastly by name (or whatever I want to).

**Comment by justinleewells** [comment]
This is an excellent idea.

**Comment by numbers1311407** [comment]
I could possibly implement this over the next few days in the new front end, similar to what I'd done in the old front end in #72 but ported over to angular.

**Comment by justinleewells** [comment]
No need. I've almost got it finished. I added search as well.

**Comment by justinleewells** [comment]
Implemented in v1.2.0
