### ISSUE TITLE
"npm start" command throws "TypeError: gulp.task is not a function"

### ISSUE THREAD

**Issue by NWinocur** [justinleewells/pogo-optimizer#87]
Ubuntu LTS 16.04 with a pull from master. First attempt to use the program, so have no basis for comparison with behavior vs prior versions such as v1.0.0:

pogo-optimizer@1.1.0 start my path to/pogo-optimizer
 gulp && node index

/my path to/pogo-optimizer/gulpfile.js:13
 gulp.task('clean', function (cb) {

TypeError: gulp.task is not a function
 at Object.< anonymous > (< my path to > /pogo-optimizer/gulpfile.

This is with
node v 4.4.7
npm v2.15.8

**Comment by justinleewells** [comment]
Would you mind upgrading to the newest version of node/npm, deleting the node_modules folder, and doing a fresh npm install?

**Comment by NWinocur** [comment]
Updated to npm 3.10.5 and experienced separate issue when running npm install.  Decided instead of continuing to troubleshoot I'd rather try making a new Debian 8 virtual machine b/c from reading others' posts that sounds like a known-working environment.  Will report on results after trying.

**Comment by NWinocur** [comment]
Resolved by switching to Debian 8 and updating npm to 3.10.5.

**Comment by justinleewells** [comment]
Awesome. Glad to hear you got it working!
