### ISSUE TITLE
Stuck on loading Screen

### ISSUE THREAD

**Issue by woolynipples** [justinleewells/pogo-optimizer#88]
I'm Stuck on loading screen, got my Pc and my phone on the same network, Got my Pc's Ip witch is 192.168.1.164, and the port on the proxy for 8180, but its stuck on the loadind screen please help.

Also got the App running on my Localhost:3000

**Comment by justinleewells** [comment]
Did you set up the proxy and certificate on your phone?

**Comment by woolynipples** [comment]
Yes. i have

**Comment by justinleewells** [comment]
Are you running this in Docker?

**Comment by woolynipples** [comment]
Yes i am. 
and using this code - docker run -d -p 3000:3000 -p 8081:8081 -it cmeter/pogo-optimizer

**Comment by woolynipples** [comment]
Its like its not Connecting to the Wifi, even after i have done all the things i should have done. yesterday i got in 1 time after like an hour or around that.
