### ISSUE TITLE
BUG in pokemon names' updating. 

### ISSUE THREAD

**Issue by jzbswbsw** [justinleewells/pogo-optimizer#89]
Changing pokemon's names when optimizer is connected, it works fine, the names are updating in realtime on the report. However, if now delete(transfer) a pokemon, the names on report reverts back to the old names.

This makes it a little bit harder to organize and delete undesired pokemons.

**Comment by justinleewells** [comment]
Try the newest version and tell me if you're still getting this bug. I can't reproduce it.

**Comment by jzbswbsw** [comment]
Looks good now.
