### ISSUE TITLE
no Wifi after Proxy.

### ISSUE THREAD

**Issue by woolynipples** [justinleewells/pogo-optimizer#90]
I've got no Wifi after i connect to the proxy. Got my firewall down on my pc. and got the Ca.Pem from my Pc Ip address, and can see the optimizer. if i dont got the proxy on. Plz help.

Using Nexus 6P

**Comment by MarioDiar** [comment]
So you dont have wifi in your phone after setting the proxy?

**Comment by woolynipples** [comment]
I dont, have wifi net then i set it.

**Comment by MatthiasDING** [comment]
The same problem as  woolynipples.  I don't have wifi after setting the proxy.

Using Ubuntu 14.04 and Iphone6.

**Comment by MarioDiar** [comment]
Are you guys installing from the latest commit?

**Comment by woolynipples** [comment]
How did you fix it tho ?? can't seem to find a way to get it to work at this point.

**Comment by mathiasbynens** [comment]
I may be misunderstanding the issue here, but have you reset the wifi settings on your phone? You’ll want to undo the steps explained in the README: https://github.com/justinleewells/pogo-optimizer#phone-setup Set “Proxy” to “none”.

**Comment by woolynipples** [comment]
No that is not the problem, the problem is then i connect to the Proxy there is no wifi, to get on the app to update the program on my pc, that is the problem

**Comment by MarioDiar** [comment]
@woolynipples I believe this is the same thing that is happening to you.

https://github.com/justinleewells/pogo-optimizer/issues/74

**Comment by woolynipples** [comment]
i'm using Pc not Mac. btw

**Comment by MarioDiar** [comment]
You are using docker? I believe it's the same steps anyway.

**Comment by justinleewells** [comment]
https://www.reddit.com/r/TheSilphRoad/comments/4ufhil/pokemon_go_optimizer_v120_now_with_better/d5qik12?context=3

Maybe this? The netsh stuff is probably what you're missing.

**Comment by woolynipples** [comment]
Found this and it works Well. 

https://www.reddit.com/r/TheSilphRoad/comments/4tqddw/guide_to_determine_exact_ivs_using_mitm_proxy?sort=new

**Comment by justinleewells** [comment]
Okay, but that doesn't really pertain to this program.
