### ISSUE TITLE
Some Pokemon are highlighted in orange instead of gray

### ISSUE THREAD

**Issue by jordansmellie** [justinleewells/pogo-optimizer#91]
In v 1.1.0 of Optimizer (OS X environment), three of my Pokemon have their sprite and name highlighted in bright orange, rather than gray/black like all the others. 

I can find no similarities among these three. They are a Hypno, a Jynx, and an Electabuzz. When sorted by number, Fast move, or CP, two are next to each other but the third is still elsewhere in the list. When sorted by all other categories, they are all separate from one another. There's nothing in common in their names- the Jynx is alphanumeric with no spaces, the Electabuzz is alphanumberic with one space, and the Hypno includes both a space and a special character (the greater-than sign > ). The orange highlighting is present across all four permutations of the Move and IV switches.

If this orange highlighting is a feature, its purpose is not evident. Any guesses why this is happening?

**Comment by justinleewells** [comment]
It indicates that the Pokemon are favorited.

**Comment by jordansmellie** [comment]
Oh geez. The one thing I didn't check. Thanks!

**Comment by justinleewells** [comment]
I'll think of some way to convey the meaning better!
