### ISSUE TITLE
Caching problems - accounts merged

### ISSUE THREAD

**Issue by wererogue** [justinleewells/pogo-optimizer#93]
Tested with the version from ~11am EST today

If two different accounts are logged in to the same instance of pogo optimizer, simultaneously or sequentially, the optimizer will show pokemon from both accounts until the docker container is restarted.

**Comment by justinleewells** [comment]
There's really no workaround for that. The best I can do is log out the first player if a second tries to connect, but there are cases where it could bypass that.

**Comment by wererogue** [comment]
¯\_(ツ)_/¯ we can work around it - thanks for making the software!

If you can differentiate the traffic between the two accounts a dropdown to filter by account would be lovely, but otherwise we'll just make sure we wipe after using.

**Comment by justinleewells** [comment]
There's no real way to differentiate between traffic atm. I'll dig through the mitm library and see if there's any way to expose it.

**Comment by lyxhaven** [comment]
I encountered the same issue. How do I wipe one of the account ? I'm going to use only one account from now on.

**Comment by justinleewells** [comment]
If you're using Docker, just delete the container and create another one. If you're not, then just delete the /data/<username> folder.
