### ISSUE TITLE
need your help.

### ISSUE THREAD

**Issue by danieledifice** [justinleewells/pogo-optimizer#94]
I have successfully using v1.0 before, after the new releases available I tried to reinstall from the beginning. So I type brew uninstall protobuf and deleted pogo optimizer from my library, after that I'm once again install it from beginning, start from "brew install --devel protobuf" (success) then "sudo npm install -g bower" (success) until "sudo npm install -g gulp" I'm getting this error:
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

help me, I like THIS very much. Thanks a lot

**Comment by justinleewells** [comment]
I think those are just warnings. I don't believe that they will hurt anything.

**Comment by danieledifice** [comment]
thanks a lot, it's work perfectly, love the update. 👍
