### ISSUE TITLE
Floating name row

### ISSUE THREAD

**Issue by sigboe** [justinleewells/pogo-optimizer#96]
Please make the row that has the name for all the columns float when you scroll past it.

**Comment by alanchengg** [comment]
This is one of the first things I've noticed about using this proxy. I could take a wack at this in a bit.

**Comment by justinleewells** [comment]
I've already got this implemented on a local branch. It'll be pushed later today.

**Comment by sigboe** [comment]
I did a git pull, but the top row still does not float :(
